### PR TITLE
Create gameboy.c & move gameboy.h implement to gameboy.c

### PR DESCRIPTION
**Pull request by Rsysz**
Is this ok?

### CODE REVIEW

**Comment by jserv** [comment]
The changes are huge. Please check this: https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/
Only one functional change should be submitted.

**Comment by jserv** [comment]
Also, the commit message should be revised. Read this article carefully: https://chris.beams.io/posts/git-commit/

**Comment by Rsysz** [comment]
Should I create a branch and send pull request several times?

**Comment by jserv** [comment]
> Should I create a branch and send pull request several times?

No exactly. You should create several branches and send a few pull requests which reflect the functional changes.

**Comment by jserv** [comment]
For the very beginning, I expect that you can decouple instruction-specific changes from the single header along with its test case(s). Then, you send the pull request which refers to the decoupling.

**Comment by jserv** [comment]
If you CAREFULLY read the articles I mentioned earlier, you shall already understand the considerations.

**Pull request closed without merging**
