### PR TITLE
Move the gbz80 instruction implementation to the dedicated C source

### PR DESCRIPTION
**Pull request by Rsysz**
Move __gb_step_cpu function implement to gameboy.c
but didn't change Makefile, it will be add after few commits

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
Change the subject of pull request and git commit message to "Move the gbz80 instruction implementation to the dedicated C source"

**Comment by jserv** [comment]
File name `gameboy.c` might be confusing. How about `cpu.c` or `instructions.c`?

**Comment by Rsysz** [comment]
> File name `gameboy.c` might be confusing. How about `cpu.c` or `instructions.c`?

`__gb_step_cpu` will be moved to `cpu.c` after few commits
As for now, I just try to move `gameboy.h` implementation to dedicated C source file

**Comment by jserv** [comment]
> > File name `gameboy.c` might be confusing. How about `cpu.c` or `instructions.c`?
> 
> `__gb_step_cpu` will be moved to `cpu.c` after few commits
> As for now, I just try to move `gameboy.h` implementation to dedicated C source file

You can submit the corresponding git commit(s) within this pull request. However, we should avoid naming a file with uncertain `gameboy.c`, which is not beneficial for further understanding.

**Comment by Rsysz** [comment]
I will send pull request after rearrange my commits

**Pull request closed without merging**
